# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 23:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0002_auto_20150606_2003'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_picture', to='filer.Image'),
        ),
    ]
